# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a6d6f4013e52ccc7d91d325c144b65c5f161d1df8309f2671667688ccaad638a23a85d31650ecc3da6d1632843131322064eb66bb264265076ebb2bf24c2e6

test:
  secret_key_base: 848603aa8975930d85e695269b634b083c50b9c34c437889425c59748942271435c2be1505903adad3ce5b37b7997967435a0b094ff4ce5f9eb5a342dd638344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
